import pandas as pd
from sqlalchemy import create_engine
import os

# Load the CSV file generated by data-acquisition.py
csv_path = "data/raw/sp100_1y.csv"
df = pd.read_csv(csv_path)

# Database connection settings (edit as needed)
POSTGRES_USER = os.getenv('POSTGRES_USER', 'postgres')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD', 'password')
POSTGRES_DB = os.getenv('POSTGRES_DB', 'momentum')
POSTGRES_HOST = os.getenv('POSTGRES_HOST', 'localhost')
POSTGRES_PORT = os.getenv('POSTGRES_PORT', '5432')

# Create SQLAlchemy engine for PostgreSQL
engine = create_engine(f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}")

# Push DataFrame to PostgreSQL (replace 'sp100_ohlcv' with your table name)
df.to_sql('sp100_ohlcv', engine, if_exists='replace', index=False)
print("Data pushed to PostgreSQL table 'sp100_ohlcv'.")
